### ISSUE TITLE
Work Together To Install plots2 on your Local Machine(Setup)

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#10844]
Also a heads up:  if you are installing the `plots2` project on your local, maybe consider using sqlite3 for database 
. On step **7** choose the second option, 
> If sqlite3, run `cp config/database.yml.sqlite.example config/database.yml` to make a copy of config/database.yml.sqlite.example in config/database.yml. kindly note if you choose to use sqlite some tests may fail. The project was setup initially to use mysql and some tests are tailored for mysql db. No need for alarm, we are working to fix these and this will not interfere with your development process

As we are having issues reported by folks using `mysql2`

_Originally posted by @cesswairimu in https://github.com/publiclab/plots2/issues/10840#issuecomment-1079627068_

**Comment by TildaDares** [comment]
Leave a comment here with the details of the errors you're facing. Thank you!

**Comment by akanbifatimah** [comment]
HI @TildaDares , I have been able to run infragram on my local machine , do I need to install plot2 in order to work on this project

**Comment by TildaDares** [comment]
Hi @akanbifatimah, no you don't have to install plots2.

**Comment by akanbifatimah** [comment]
alright,Thank you

**Comment by untari** [comment]
Hi @TildaDares I'm participating on outreachy, do we have to contribute to the project that listed for the outreachy, or we can contribute to other repo too? Thanks!

**Comment by cesswairimu** [comment]
Hi @untari, you can contribute to other repos too. thanks

**Comment by untari** [comment]
Hi @cesswairimu, noted with thanks!

**Comment by stephaniequintana** [comment]
@ishikajn8126, it appears we may have run into the same issue. My Mac would not download `rvm` or `rbenv` due to an SSL certificate problem. In addition to the errors you mentioned, I received the following when I tried to run `curl -L https://get.rvm.io | bash -s stable`. 

![Screen Shot 2022-03-22 at 4 30 10 PM](https://user-images.githubusercontent.com/81270711/160566557-5237d698-363e-4ee8-9b8d-08d7fc8a2e1a.png)

If you're experiencing the same, please reach out to me. I found a quick and easy way to bypass this.

Also, please be advised that many in the community work exclusively with/through [gitpod](https://publiclab-plots2-ana0i5g7064.ws-us38.gitpod.io/), it's a great alternative to setting up your local environment and you'll be immediately up and running.

**Comment by ishikajn8126** [comment]
> Hi @ishikajn8126, have you installed `rbenv` or `rvm`? https://github.com/publiclab/plots2/blob/main/doc/PREREQUISITES.md#ruby

Hey @TildaDares, yeah i seem to have skipped the prerequisities...
Got that issue resolved now!

**Comment by ishikajn8126** [comment]
> @ishikajn8126, it appears we may have run into the same issue. My Mac would not download `rvm` or `rbenv` due to an SSL certificate problem. In addition to the errors you mentioned, I received the following when I tried to run `curl -L https://get.rvm.io | bash -s stable`.
> 
> ![Screen Shot 2022-03-22 at 4 30 10 PM](https://user-images.githubusercontent.com/81270711/160566557-5237d698-363e-4ee8-9b8d-08d7fc8a2e1a.png)
> 
> If you're experiencing the same, please reach out to me. I found a quick and easy way to bypass this.
> 
> Also, please be advised that many in the community work exclusively with/through [gitpod](https://publiclab-plots2-ana0i5g7064.ws-us38.gitpod.io/), it's a great alternative to setting up your local environment and you'll be immediately up and running.

Hey @stephaniequintana! Thanks a lot for offering support!!
I got that issue resolved!

**Comment by Forchapeatl** [comment]
@TildaDares   I was able to resolve this issue [4396](https://github.com/publiclab/plots2/issues/4396) . The error occurs when step 6 of the installation guide is skipped.

**Comment by PeculiarE** [comment]
> If you're experiencing the same, please reach out to me. I found a quick and easy way to bypass this.
> 
> Also, please be advised that many in the community work exclusively with/through [gitpod](https://publiclab-plots2-ana0i5g7064.ws-us38.gitpod.io/), it's a great alternative to setting up your local environment and you'll be immediately up and running.

Hello @stephaniequintana. So I did try starting the app on gitpod. But got this error:

<img width="872" alt="Screenshot 2022-03-29 at 23 38 25" src="https://user-images.githubusercontent.com/75625011/160718350-ff782f40-670f-4f1a-82e9-942cfea06c26.png">

Have you been able to succesfully run the app on gitpod?

**Comment by stephaniequintana** [comment]
@PeculiarE, the original error I was referring to, above, is the one pertaining to the SSL Certificate problem. I solved that on (on my Mac) by bypassing the curl security and I was then, finally, able to download rvm. I was still unable to setup my local environment, view the thread starting here: https://github.com/publiclab/plots2/issues/4936#issuecomment-1075936910.

To your specific question, I did finally get GitPod to run successfully. I **cannot advise you on what to do**, but I will tell you what I did. Firstly, per the above thread, I incorrectly ran `passenger start` in GitPod. This is not necessary as it is already configured in `plots2/.gitpod.yml` to do so. The next time I opened the repo in GitPod, there were a multitude of differences between my forked branch and the origin (mostly due to everything under the sun I was downloading to get zsh to cooperate with rvm). Rather than ignoring those, or squashing specific commits or rebasing to an earlier commit, or ...(there were many ways I could have remedied my branch)... I deleted the repo and started with a freshly forked one. After that, pending the VERY long build, the error page was no longer there and the app now runs smoothly.

I'm sorry I cannot provide more specific direction. Although, I do highly recommend asking the group. I'm a bit blown away by the knowledge and willingness to help that everyone here seems to have ❤️

**Comment by ishikajn8126** [comment]
Hey everyone!
I got stuck with another error at step 5 of standard installation, which occurred on running the command `bundle install` :
Would really appreciate any help in this regard..!

![Screenshot from 2022-03-30 11-49-12](https://user-images.githubusercontent.com/72145053/160764888-82b54924-391b-4bfd-8059-ffee7c2c2c26.png)

![Screenshot from 2022-03-30 11-49-25](https://user-images.githubusercontent.com/72145053/160764911-d22ff922-bb12-4cf4-b4d2-cc688d835a83.png)

![Screenshot from 2022-03-30 11-49-45](https://user-images.githubusercontent.com/72145053/160764916-714baa9d-350e-486a-90a4-d5821d0b18d3.png)

**Comment by TildaDares** [comment]
Hi @ishikajn8126, do you have nodejs installed? You can install it by running `sudo apt-get install nodejs`

**Comment by PeculiarE** [comment]
Thank you, @stephaniequintana. So, I wasn't running GitPod on my fork but directly from the main repo. Even tried setting it up on my local machine but kept on encountering one error or the other. Eventually, I followed your advice: deleted my existing fork, re-forked, and then tried running it again on GitPod. Had to change the db configuration in the database.yml file to an sqlite3 db before it eventually worked. Thank you so much!

**Comment by PeculiarE** [comment]
@ishikajn8126 When I tried setting up the project on my machine too, I faced this error even though I had nodejs already installed. But luckily for me, the error message also told me the command to run to fix it. The command was quite long and I can't remember it exactly. And sadly, recent console messages in my terminal have overwritten it. 😢 😞 

I would suggest exactly what @stephaniequintana said. Try running the project on GitPod instead. It will save you time because even though I fixed this error you're facing now, I encountered like 6 more ahead and the app didn't still run perfectly after trying to fix all of them.

If you do have any issues running it on GitPod, please feel free to reach out to either me or Stephanie as it is working quite well for both of us 😄

**Comment by illyShelly** [comment]
Hello @TildaDares , 
I would like to point to one thing and differences which I found out during installation and reading files. The link you  mentioned above `for standard installation` link: [](https://github.com/publiclab/plots2/blob/master/README.md) differs from the Readme file for plot2 repo link:  [https://github.com/publiclab/plots2#standard-installation]

Especially, in **version of ruby** 2.7.3 vs. 2.4.4, 
- then older way to run command to exclude mysql db (`--without `), 
- point 10. there is missing this line: `Setup React & webpacker by running rails webpacker:install && rails webpacker:install:react && rails generate react:install` and info about prompt what to do so, or better to say not to do.

**Comment by stephaniequintana** [comment]
@PeculiarE, I'm so glad to learn you're up and running.
> P.S. Did you have to tweak your database.yml file as well? Or it worked for you right out of the bag?

I actually tweaked the file (commented out the sql directive) initially. Though I meant to, I never went back to see if it would worked without the directive commented out. 

Honestly, I experienced so many issues trying to set up locally that once I realized I can work (and gain experience) with GitPod, I never looked back. When I find some time, I will try again (bc I LOVE my VScode setup), but the errors I encountered and the (embarrassingly) amount of time I wasted coupled with the time constraints were outweighed by my excitement to get started. @ishikajn8126, I hope you're finally set up, too. If not, @PeculiarE makes an excellent point towards the time you will save (and from our personal experience, the errors you are likely to encounter in the upcoming steps).

Cheers, all - I hope everyone is having a great day!

**Comment by Forchapeatl** [comment]
> 

@PeculiarE . Here is the solution [https://github.com/publiclab/plots2/issues/4396#issuecomment-1079781786](https://github.com/publiclab/plots2/issues/4396#issuecomment-1079781786)

**Comment by Forchapeatl** [comment]
> > If you're experiencing the same, please reach out to me. I found a quick and easy way to bypass this.
> > Also, please be advised that many in the community work exclusively with/through [gitpod](https://publiclab-plots2-ana0i5g7064.ws-us38.gitpod.io/), it's a great alternative to setting up your local environment and you'll be immediately up and running.
> 
> Hello @stephaniequintana. So I did try starting the app on gitpod. But got this error:
> 
> <img alt="Screenshot 2022-03-29 at 23 38 25" width="872" src="https://user-images.githubusercontent.com/75625011/160718350-ff782f40-670f-4f1a-82e9-942cfea06c26.png">
> 
> Have you been able to succesfully run the app on gitpod?

@PeculiarE  here is the solution [https://github.com/publiclab/plots2/issues/4396#issuecomment-1079781786](https://github.com/publiclab/plots2/issues/4396#issuecomment-1079781786)

**Comment by TildaDares** [comment]
> `for standard installation` [https://github.com/publiclab/plots2#standard-installation](url) differs from the Readme file for plot2 repo link: https://github.com/publiclab/plots2/blob/master/README.md

Hi @illyShelly, thank you for the observation! We no longer make use of the `master` branch so it's the README on the `main` branch you should use https://github.com/publiclab/plots2/blob/main/README.md

**Comment by illyShelly** [comment]
@TildaDares got it 😄 I have no idea how I get there.

**Comment by PeculiarE** [comment]
Thanks @stephaniequintana for your response. Lol...I know how that feels, wasting a lot of time trying to debug locally. But yeah, we're lucky we have GitPod to save the day 😅 

@Forchapeatl .....thank you for your help. However, I did check out that thread while debugging on my local and implemented your suggestion but it didn't resolve my issue 😢. Plus, the error-message screenshot I shared was gotten when I was trying to run the app on GitPod and not on my local machine. I fixed it by simply starting the whole forking process afresh, tweaked the database.yml file on GitPod and seeded the database. And everything was well.

**Comment by ishikajn8126** [comment]
> Hi @ishikajn8126, do you have nodejs installed? You can install it by running `sudo apt-get install nodejs`

Hey @TildaDares, tried installing nodejs and running `bundle install` again, it's still giving the same error. I've got the project on running on gitod though..!

Hey @PeculiarE @stephaniequintana, thanks a lot for your inputs, I've got the project running on gitpod and opened a PR as well..

**Comment by PeculiarE** [comment]
Awesome news @ishikajn8126 and you're very welcome 😄

**Comment by stephaniequintana** [comment]
@simransia, just brainstorming here...has it finished loading? When I use GitPod it tends to take quite a while for all the dependencies to load and then for the app to run. I see this error screen until the loading is complete...

**Comment by simransia** [comment]
@stephaniequintana yes mam it also took a while for loading all the dependencies in my browser as well. After the loading was completed I was not able to see the live preview of the application. So in the terminal I run the command "passenger start" and then this error page appears.

**Comment by stephaniequintana** [comment]
@simransia, I've successfully opened plots2 in GitPod. At your convenience, please try it again  - do ensure you are opening it from the fork in your repository. FYI, it took almost 8 minutes for the browser window to open, so please don't get discouraged, grab yourself a drink and be patient, it should be up and running soon!

**Comment by simransia** [comment]
Congratulations to you for opening it successfully !! But I am still unable to see the live preview of the page even after waiting for 30 minutes. 😅 And yes I am opening it from the forked repository.

 <img src="https://user-images.githubusercontent.com/88017902/162232136-13f5d511-e48e-4c0b-9709-d5e4cdf81572.png" width="400" height="250" align="center" />
This is how my gitpod worksplace looks like write now.

I hope I will find it's solution soon.

**Comment by stephaniequintana** [comment]
@simransia, I'm not sure what the problem could be. After I was unable to get my local environment setup, I had to re-fork the project in order to successfully open it on GitPod. I know that @PeculiarE has also solved the issue she had with GitPod, I believe she also re-forked the repo (& she may have had to commented out one of the database directives). Hopefully she will be able to tell us more specifically what she did and that will work for you as well. 

At this point, please post in the Gitter chat in case someone there has experienced/solved the same. I understand that the browser in GitPod is not opening/updating. I do hope that you are still able to access and edit the files in the app. I'm sorry I couldn't help you more, I hope it's successfully running soon.

**Comment by simransia** [comment]
Thankyou @stephaniequintana for your efforts which you have put in trying to solve my issue. 
@PeculiarE could you please tell me what changes you have made in the database directive ? Because that might solve my problem as well.

**Comment by stephaniequintana** [comment]
@simransia, you're most welcome. I wish I could have done more. 

I see that you've reached out on Gitter, I was hoping someone there might have been able to help. Of course, I don't know what all you have tried, but per the [comments above](https://github.com/publiclab/plots2/issues/10844#issuecomment-1082842641) both @PeculiarE and I were able to delete our forks and then a re-fork finally opened...I would otherwise ensure that you have pulled all of the latest changes from the origin. It just doesn't make sense that it is working for others.

Per the thread [here](https://github.com/publiclab/plots2/issues/4936#issuecomment-1075936910), it is in the Gemfile where we toyed with commenting out the sql directive:
```
group :mysql, :production, :development, :test do
  gem 'mysql2', '>= 0.4.4'
  # mysql 0.4.3+ causes a version mismatch, apparently, and demands 'activerecord-mysql2-adapter'
end
```

She and I merely discussed this, I'm uncertain whether she did or did not make this change or if it did or did not have any affect on GitPod.

#### Possible other things you might try:
* The SSL in Development directive/instructions in the plots2 [README.me](https://github.com/publiclab/plots2)
* Installing the Google GitPod extension (if you haven't already) 
* If you were unable to set up your local environment, let us know on Gitter - it is very likely that someone there has solved your issue
* The entirety of [this thread](https://github.com/publiclab/plots2/issues/4936) contains multiple issues you may have encountered
* The first comment in [this thread](https://github.com/publiclab/plots2/issues/3840) mentions that [https://codenvy.io](https://developers.redhat.com/products/codeready-workspaces/overview) was an alternative - although that comment was 4 years ago and I have no other information about it, you might reach out to the mentors to see if that is still an option (also be aware that the other comments concerning manifest.js are no longer valid).

Lastly, know that setting up plots2 is not a requirement for participating in the internship. I understand that it is highly desired, but it by no means disqualifies you.

I hope any of the above helps, @simransia!

**Comment by akanbifatimah** [comment]
@stephaniequintana Thank you so much for all your help so far, just like @simransia , I am also on windows OS and haven't been able to run plot2 either via gitPod or on my local machine.  I reached out to @PeculiarE who successfully ran the project on gitpod after facing some issues while trying to run on her local machine (Mac Os), she mentioned doing some editing in her database.yml file which fixed the error she was getting and have since been able to run it successfully on git Pod.
However I tried same but still haven't been able to run it successfully via git Pod. My other option is to try running it via my Local Machine. That has not been easy too, as installing rvm 2.7.3 still throws error. 

So I generally think it's an error associated with running ruby on windows. 

@kunmi02 has been very helpful, if we are able to run plot2 locally on a Windows OS, I will definitely post the solutions here.

So sorry @simransia , I totally understand how stressful this could be, hopefully, it should be resolved soon.

**Comment by stephaniequintana** [comment]
@simransia and @akanbifatimah, do also try googling the errors or your system info + gitpod connection errors...github is such a vast network, we may find the answer in the wild. 🍀

**Comment by kunmi02** [comment]
Thank you @akanbifatimah .

I and @akanbifatimah have been trying to set up plot2 locally. We were able to install rvm on windows, the issue now is setting up rvm with ruby 2.7.3. Whenever we run the rvm list we get this error `ruby-2.7.3 [ missing bin/ruby ]`.

We will continue debugging and I believe we will have a solution soon.

**Comment by stephaniequintana** [comment]
@kunmi02 and @akanbifatimah, I assume you've tried everything under the sun...I had the same(ish) issue on my Mac and it was due to a certificate error. I won't make you hash it all out again, but I found [this](https://stackoverflow.com/questions/29876386/how-to-fix-rvm-gems-missing-bin-ruby) for you. It is along the lines of what cleared up my issue.

**Comment by akanbifatimah** [comment]
> @kunmi02 and @akanbifatimah, I assume you've tried everything under the sun...I had the same(ish) issue on my Mac and it was due to a certificate error. I won't make you hash it all out again, but I found [this](https://stackoverflow.com/questions/29876386/how-to-fix-rvm-gems-missing-bin-ruby) for you. It is along the lines of what cleared up my issue.

Thank you so much @stephaniequintana

**Comment by kunmi02** [comment]
@stephaniequintana I am running a mac system and I have no issues with installation. The installation we are working on now is on a windows system. Thanks for the solution shared. We will definitely try that out and share outcome

**Comment by imranburki** [comment]
Hi I am facing error while installing ruby.
![Screenshot from 2022-04-09 12-15-59](https://user-images.githubusercontent.com/56333970/162561410-b46397e7-4a28-43d4-acc0-132982dd5371.png)

**Comment by Forchapeatl** [comment]
> Hi I am facing error while installing ruby. ![Screenshot from 2022-04-09 12-15-59](https://user-images.githubusercontent.com/56333970/162561410-b46397e7-4a28-43d4-acc0-132982dd5371.png)

I faced this issue some time ago  run 
 Disable RVM from trying to install necessary software via apt-get
`rvm autolibs disable`
 Then try installing Ruby:
`rvm install 2.4.0`

reference [https://stackoverflow.com/a/42286377](https://stackoverflow.com/a/42286377)

**Comment by kunmi02** [comment]
@simransia I think i have a fix for your issue. I got the same error on gitpod too and I was able to fix it finally. I had the same error on gitpod too 

<img width="1440" alt="Screenshot 2022-04-09 at 23 27 13" src="https://user-images.githubusercontent.com/27483062/162594600-2d8bec5e-144b-40b9-9077-2a737d5dd9bb.png">

The first thing I did was to stop the passenger server by pressing ctrl + c.
Then I did a `yarn install`. I did this because I though the issue would be from package.json file.
Yarn install gave me this error
`$ yarn install
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["grow-textarea@https://github.com/jywarren/grow.git#d54141c9456343f14cc6c935faa0915af09eb669"] is trying to unpack in the same destination "/home/gitpod/.cache/yarn/v6/npm-grow-textarea-1.0.1-d54141c9456343f14cc6c935faa0915af09eb669/node_modules/grow-textarea" as pattern ["grow-textarea@git://github.com/jywarren/grow.git#d54141c9456343f14cc6c935faa0915af09eb669"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["woofmark@https://github.com/jywarren/woofmark.git#plots2"] is trying to unpack in the same destination "/home/gitpod/.cache/yarn/v6/npm-woofmark-4.0.3-78821fad8687757a4201fbef3be4b85418e785ef/node_modules/woofmark" as pattern ["woofmark@git://github.com/jywarren/woofmark.git#plots2"]. This could result in non-deterministic behavior, skipping.
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/jywarren/grow.git
Directory: /workspace/plots2
Output:
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`
the i did ran this command to fix the error `git config --global url."https://github.com/".insteadOf git://github.com/`

than I ran yarn install again for the package to be installed.
Afterwards, i tried to start the server again by running passenger start but I got the error below

<img width="1440" alt="Screenshot 2022-04-09 at 23 37 24" src="https://user-images.githubusercontent.com/27483062/162594587-c8f51cc1-3ebd-4712-b5d1-ad86d968bf6c.png">

so  I stoped the server again by typing ctr + c then I ran this command `rake assets:precompile` after that I ran `bundle install` finally I did this `bundle exec rails webpacker:install` - it installs webpacker and restart the webpacker server.
While running this command bundle exec rails webpacker:install`, it will ask you something like this :
`conflict  config/webpacker.yml
Overwrite /workspace/plots2/config/webpacker.yml? (enter "h" for help) [Ynaqdhm] ` please just type `n`
that is saying that you dont want the installation to overwrite the existing file.
After that, i started the server again with passenger start and I am in.

Hope this helps

**Comment by stephaniequintana** [comment]
Thank you, @kumni02. There was similar issue/fix with #10827, Im curious if/how they're related, At any rate, we all appreciate the effort and sharing the details/results.

**Comment by simransia** [comment]
Woow @kunmi02 !!  You are really really awesome. 💛💛 I followed all the instructions you have given and now the problem is fixed. 💃🥳

Thank You so much for providing help 🙇‍♀️
I highly appreciate it !🥰

**Comment by Ademola101** [comment]
Hi, I am an outreachy aspirant, I am getting this error when installing the plot2 on my local machine.

An error occurred while installing critical-path-css-rails (4.1.1), and Bundler cannot continue.
Make sure that `gem install critical-path-css-rails -v '4.1.1' --source 'https://rubygems.org/'` succeeds before bundling.

**Comment by Forchapeatl** [comment]
> 

@Ademola101 , can you share a screen shot of the error with us

**Comment by Ademola101** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/54910756/162716435-762aba25-9c4b-4069-bb58-cbaec0780653.png)
@Forchapeatl this is the error i am getting

**Comment by kunmi02** [comment]
Hi @Ademola101 try run `gem install crtical-path-css-rails -v '4.1.1' --source 'https://rubygems.org/'`  on your terminal within the project roo folder.
After running that try run `bundle install` again

**Comment by Ademola101** [comment]
Thanks @kunmi02.

This is what I  get after running that
![Screenshot (7)](https://user-images.githubusercontent.com/54910756/162728176-5910bf7b-c672-4fe1-b170-94cfc26e9943.png)

**Comment by Forchapeatl** [comment]
> ![Screenshot (6)](https://user-images.githubusercontent.com/54910756/162716435-762aba25-9c4b-4069-bb58-cbaec0780653.png) @Forchapeatl this is the error i am getting
seems like your gem version is not compatible with windows
first check your gem version
 `gem -v`
if it's > 2.3.0  run 
`gem update --system 2.3.0`
then bundle install

reference [https://stackoverflow.com/a/25621469](https://stackoverflow.com/a/25621469)

**Comment by kunmi02** [comment]
oooppss...
@Ademola101 I don't think you can run a rails app successfully on the windows system. If at all you proceed ahead of this stage, you might get stuck at the point of installing ruby using rvm cos rvm does not support windows.

In conclusion, I will advise you use WSL to setup the project or move to Linux or Mac system

**Comment by PeculiarE** [comment]
Wow @kunmi02....that's a pretty long and detailed solution. Where were you when I was having issues running plots2 on Gitpod 🤣 🤣....On a more serious note though, I'm glad it worked for you @simransia 🥳 🥳 . As @stephaniequintana and @akanbifatimah already mentioned, I fixed my issue by switching from a mysql db to an sqlite one in the database.yml file, and surprisingly that worked for me. Unfortunately, I couldn't replicate that success when trying to help @akanbifatimah set up hers 😞 
On that note, @akanbifatimah...were u able to finally get GitPod running following @kunmi02's very detailed debugging process above?  😄 😄

**Comment by Ademola101** [comment]
> Thanks @kunmi02.
> 
> This is what I get after running that ![Screenshot (7)](https://user-images.githubusercontent.com/54910756/162728176-5910bf7b-c672-4fe1-b170-94cfc26e9943.png)

Thanks, It was because I was using old version of bundler.

**Comment by akanbifatimah** [comment]
> Wow @kunmi02....that's a pretty long and detailed solution. Where were you when I was having issues running plots2 on Gitpod 🤣 🤣....On a more serious note though, I'm glad it worked for you @simransia 🥳 🥳 . As @stephaniequintana and @akanbifatimah already alluded to, I fixed my issue by switching from a mysql db to an sqlite one in the database.yml file, and surprisingly that worked for me. Unfortunately, I couldn't replicate that success when trying to help @akanbifatimah set up hers 😞 On that note, @akanbifatimah...were u able to finally get GitPod running following @kunmi02's very detailed debugging process above? 😄 😄

Yes I have been able to run plot2 via gitpod @PeculiarE ,thank you for asking dear. @kunmi02 thank you so much for guiding me through.
Thank you, everyone, for all your suggestions, I learned a lot from this process.

**Comment by Ademola101** [comment]
Installing webpacker and react. There are some file conflict, should I accept or reject it
![Screenshot (8)](https://user-images.githubusercontent.com/54910756/163022215-9ffccf1c-6bf9-4bca-8092-dcadaeec9f7b.png)

**Comment by kunmi02** [comment]
@Ademola101 please reject it. Type `n` and press enter

**Comment by Ademola101** [comment]
@kunmi02 Thank you. However, I am getting this error after I start the server by passenger start
![Action Controller_ Exception caught - Google Chrome 13_04_2022 10_13_49 am](https://user-images.githubusercontent.com/54910756/163143353-673362ae-f627-4eeb-8a92-4197d11e530f.png)

**Comment by kunmi02** [comment]
@Ademola101 Kindly follow the steps I share here https://github.com/publiclab/plots2/issues/10844#issuecomment-1094139973

**Comment by Ademola101** [comment]
My development server is so slow and often bring out this error:


The Phusion Passenger(R) application server tried to start the web application, but this took too much time, so Passenger put a stop to that.

The stdout/stderr output of the subprocess so far is:
[fog][DEPRECATION] Unable to load Fog::Google::Compute
[fog][DEPRECATION] Falling back to deprecated constant Fog::Compute::Google. The preferred format of service provider constants has changed from service::provider to provider::service. Please update this service provider to use the preferred format.
[fog][DEPRECATION] Unable to load Fog::Google::DNS
[fog][DEPRECATION] Falling back to deprecated constant Fog::DNS::Google. The preferred format of service provider constants has changed from service::provider to provider::service. Please update this service provider to use the preferred format.
[fog][DEPRECATION] Unable to load Fog::Google::Storage
[fog][DEPRECATION] Falling back to deprecated constant Fog::Storage::Google. The preferred format of service provider constants has changed from service::provider to provider::service. Please update this service provider to use the preferred format.
/usr/share/rvm/gems/ruby-2.7.3/gems/nokogumbo-2.0.4/lib/nokogumbo/html5.rb:13: warning: already initialized constant Nokogiri::HTML5::HTML_NAMESPACE
/usr/share/rvm/gems/ruby-2.7.3/gems/nokogiri-1.13.3-x86_64-linux/lib/nokogiri/html5.rb:231: warning: previous definition of HTML_NAMESPACE was here
/usr/share/rvm/gems/ruby-2.7.3/gems/nokogumbo-2.0.4/lib/nokogumbo/html5.rb:14: warning: already initialized constant Nokogiri::HTML5::MATHML_NAMESPACE
/usr/share/rvm/gems/ruby-2.7.3/gems/nokogiri-1.13.3-x86_64-linux/lib/nokogiri/html5.rb:232: warning: previous definition of MATHML_NAMESPACE was here
/usr/share/rvm/gems/ruby-2.7.3/gems/nokogumbo-2.0.4/lib/nokogumbo/html5.rb:15: warning: already initialized constant Nokogiri::HTML5::SVG_NAMESPACE
/usr/share/rvm/gems/ruby-2.7.3/gems/nokogiri-1.13.3-x86_64-linux/lib/nokogiri/html5.rb:233: warning: previous definition of SVG_NAMESPACE was here
/usr/share/rvm/gems/ruby-2.7.3/gems/nokogumbo-2.0.4/lib/nokogumbo/html5.rb:16: warning: already initialized constant Nokogiri::HTML5::XLINK_NAMESPACE
/usr/share/rvm/gems/ruby-2.7.3/gems/nokogiri-1.13.3-x86_64-linux/lib/nokogiri/html5.rb:234: warning: previous definition of XLINK_NAMESPACE was here
/usr/share/rvm/gems/ruby-2.7.3/gems/nokogumbo-2.0.4/lib/nokogumbo/html5.rb:17: warning: already initialized constant Nokogiri::HTML5::XML_NAMESPACE
/usr/share/rvm/gems/ruby-2.7.3/gems/nokogiri-1.13.3-x86_64-linux/lib/nokogiri/html5.rb:235: warning: previous definition of XML_NAMESPACE was here
/usr/share/rvm/gems/ruby-2.7.3/gems/nokogumbo-2.0.4/lib/nokogumbo/html5.rb:18: warning: already initialized constant Nokogiri::HTML5::XMLNS_NAMESPACE
/usr/share/rvm/gems/ruby-2.7.3/gems/nokogiri-1.13.3-x86_64-linux/lib/nokogiri/html5.rb:236: warning: previous definition of XMLNS_NAMESPACE was here

**Comment by Ademola101** [comment]
![Web application could not be started - Google Chrome 15_04_2022 8_49_05 am](https://user-images.githubusercontent.com/54910756/163542057-51cc40a8-7052-4dcf-8368-fd48c2f11466.png)

**Comment by kunmi02** [comment]
Hey @Ademola101 Have you been able to resolve the issue?

If you look at the passenger server, you should some errors on the server. Can you share what you see on the server here ?

**Comment by Ademola101** [comment]
> My development server is so slow and often bring out this error:
> 
> 
> The Phusion Passenger(R) application server tried to start the web application, but this took too much time, so Passenger put a stop to that.
> 
> The stdout/stderr output of the subprocess so far is:
> [fog][DEPRECATION] Unable to load Fog::Google::Compute
> [fog][DEPRECATION] Falling back to deprecated constant Fog::Compute::Google. The preferred format of service provider constants has changed from service::provider to provider::service. Please update this service provider to use the preferred format.
> [fog][DEPRECATION] Unable to load Fog::Google::DNS
> [fog][DEPRECATION] Falling back to deprecated constant Fog::DNS::Google. The preferred format of service provider constants has changed from service::provider to provider::service. Please update this service provider to use the preferred format.
> [fog][DEPRECATION] Unable to load Fog::Google::Storage
> [fog][DEPRECATION] Falling back to deprecated constant Fog::Storage::Google. The preferred format of service provider constants has changed from service::provider to provider::service. Please update this service provider to use the preferred format.
> /usr/share/rvm/gems/ruby-2.7.3/gems/nokogumbo-2.0.4/lib/nokogumbo/html5.rb:13: warning: already initialized constant Nokogiri::HTML5::HTML_NAMESPACE
> /usr/share/rvm/gems/ruby-2.7.3/gems/nokogiri-1.13.3-x86_64-linux/lib/nokogiri/html5.rb:231: warning: previous definition of HTML_NAMESPACE was here
> /usr/share/rvm/gems/ruby-2.7.3/gems/nokogumbo-2.0.4/lib/nokogumbo/html5.rb:14: warning: already initialized constant Nokogiri::HTML5::MATHML_NAMESPACE
> /usr/share/rvm/gems/ruby-2.7.3/gems/nokogiri-1.13.3-x86_64-linux/lib/nokogiri/html5.rb:232: warning: previous definition of MATHML_NAMESPACE was here
> /usr/share/rvm/gems/ruby-2.7.3/gems/nokogumbo-2.0.4/lib/nokogumbo/html5.rb:15: warning: already initialized constant Nokogiri::HTML5::SVG_NAMESPACE
> /usr/share/rvm/gems/ruby-2.7.3/gems/nokogiri-1.13.3-x86_64-linux/lib/nokogiri/html5.rb:233: warning: previous definition of SVG_NAMESPACE was here
> /usr/share/rvm/gems/ruby-2.7.3/gems/nokogumbo-2.0.4/lib/nokogumbo/html5.rb:16: warning: already initialized constant Nokogiri::HTML5::XLINK_NAMESPACE
> /usr/share/rvm/gems/ruby-2.7.3/gems/nokogiri-1.13.3-x86_64-linux/lib/nokogiri/html5.rb:234: warning: previous definition of XLINK_NAMESPACE was here
> /usr/share/rvm/gems/ruby-2.7.3/gems/nokogumbo-2.0.4/lib/nokogumbo/html5.rb:17: warning: already initialized constant Nokogiri::HTML5::XML_NAMESPACE
> /usr/share/rvm/gems/ruby-2.7.3/gems/nokogiri-1.13.3-x86_64-linux/lib/nokogiri/html5.rb:235: warning: previous definition of XML_NAMESPACE was here
> /usr/share/rvm/gems/ruby-2.7.3/gems/nokogumbo-2.0.4/lib/nokogumbo/html5.rb:18: warning: already initialized constant Nokogiri::HTML5::XMLNS_NAMESPACE
> /usr/share/rvm/gems/ruby-2.7.3/gems/nokogiri-1.13.3-x86_64-linux/lib/nokogiri/html5.rb:236: warning: previous definition of XMLNS_NAMESPACE was here

@kunmi02 this is the error

**Comment by kunmi02** [comment]
@Ademola101 That is not the actual error. Kindly look again. There should be something you can point that could be cause of the erro. Probably database error or something

**Comment by udyanojha** [comment]
@TildaDares I'm getting this error previously I was getting issues while running on Ubuntu. So I switched to Gitpod (earlier comments suggested this way) but I'm getting this issue. <br>
Tried Deleting forked repo and reforked
Tried Running Main repo in Git pod 


![image](https://user-images.githubusercontent.com/51847297/179672273-9f0737af-ea80-428c-a9e1-505b48debd99.png)

**Comment by cesswairimu** [comment]
Hi @udyanojha, I experienced the same on my end on gitpod ; running `yarn install` solved this error, after restarting server you might get "Webpacker error" and running `rails webpacker:install`  should solved it. cc https://github.com/publiclab/plots2/issues/9871#issuecomment-1187538315

**Comment by udyanojha** [comment]
> Hi @udyanojha, I experienced the same on my end on gitpod ; running `yarn install` solved this error, after restarting server you might get "Webpacker error" and running `rails webpacker:install` should solved it. cc [#9871 (comment)](https://github.com/publiclab/plots2/issues/9871#issuecomment-1187538315)

Thank you so much!

**Comment by hsadia538** [comment]
When I run `bundle exec passenger start` I get:
<img width="711" alt="Screenshot 2022-08-03 at 4 36 42 PM" src="https://user-images.githubusercontent.com/24232785/182730585-af53322f-e025-4ec9-9b92-3c3908409e00.png">

Anyone having any idea on how to fix this?

**Comment by hsadia538** [comment]
> Hi @hsadia538, have you ran `yarn install`? That might help.

Yes I have, still the same issue.

**Comment by hsadia538** [comment]
I was able to do the setup with Gitpod and it's running. Thank you to all who commented here and suggested this way.
In my local dev environment, I am trying to log in with the username `admin` and password `password` as listed on the main page.
But it says that this user does not exist. Do I really need to do this? If yes then how

**Comment by hsadia538** [comment]
> Member

After signing up on local dev env I am getting this
<img width="1037" alt="Screenshot 2022-08-04 at 6 42 43 AM" src="https://user-images.githubusercontent.com/24232785/182861947-90ea1ee2-93d2-46a1-9ea8-fb25bb740d5c.png">

**Comment by Forchapeatl** [comment]
@hsadia538 , delete the old fork and try reforking.

**Comment by hsadia538** [comment]
@Forchapeatl This was my 3rd time reforking the repo and using gitpod to run it.
Is it necessary to get the user created?

**Comment by Forchapeatl** [comment]
@hsadia538 what database are you using Mysql or Sqlite ?

**Comment by hsadia538** [comment]
> @hsadia538 what database are you using Mysql or Sqlite ?
Sqlite.
I edited the database.yml as follows:
<img width="645" alt="Screenshot 2022-08-05 at 1 53 21 AM" src="https://user-images.githubusercontent.com/24232785/183041098-587e209c-4440-4e4f-88aa-d0d4eeed1a8d.png">

**Comment by Forchapeatl** [comment]
@hsadia538 , okay don't edit anything , just follow steps 5,6,7,8 and tel me how it goes [https://github.com/publiclab/plots2/#readme](https://github.com/publiclab/plots2/#readme)

**Comment by Forchapeatl** [comment]
of the standard [installation](https://github.com/publiclab/plots2/#standard-installation)

**Comment by hsadia538** [comment]
IT WORKED!!!

No idea what really happened, but I reforked. Redid all the steps 5,6,7,8 mentioned [here](https://github.com/publiclab/plots2/#readme) as per @Forchapeatl's advice.

Got stuck at `rails webpacker:install && rails webpacker:install:react && rails generate react:install` and it was giving me timeout. I redid the steps from `yarn install` to the last one following @kunmi02's [comment](https://github.com/publiclab/plots2/issues/10844#issuecomment-1094139973) exactly and now everything is working.
I am able to log in using the admin/moderator password.

THANKS ALOT everyone in this thread.

special thanks to @Forchapeatl and @kunmi02 . You guys are amazing!

**Comment by Forchapeatl** [comment]
you  are welcome @hsadia538

**Comment by AndroGenius-codes** [comment]
If you use  windows os and you'd like to work on this in a Linux environment install Wsl. You can find the steps in installing Wsl [Here](https://learn.microsoft.com/en-us/windows/wsl/install) 
NB: when installing the Linux distribution choose Ubuntu 20.04 as anything newer than this will give problems with the ruby installation.

**Comment by AndroGenius-codes** [comment]
i get this error after running passenger start
![bug](https://user-images.githubusercontent.com/70571088/194856949-cbdbb59b-13ad-4e4b-955e-62e2c2e43eb3.png)


@TildaDares

**Comment by TildaDares** [comment]
Hi @AndroGenius-codes, can you try stopping and starting the server?

**Comment by AndroGenius-codes** [comment]
> Hi @AndroGenius-codes, can you try stopping and starting the server?

Good evening, i was able to successfully install it. I forgot to type yarn install

**Comment by naseehasalam** [comment]
Hello I am having this issue with yarn install could someone please help me out
![Screenshot_20230724_133738](https://github.com/publiclab/plots2/assets/97714994/4037b989-0330-43f3-bc1b-e229aea3636b)

**Comment by gaurimangal14** [comment]
Hi, I'm a beginner and a Gsoc aspirant.                                                
I would like to work on this issue, so please assign me one. Thank you!!
