### ISSUE TITLE
[Setup] Work together to install plots2 on your computer

### ISSUE THREAD

**Issue by milaaraujo** [publiclab/plots2#3840]
Welcome! Getting set up can be tough, but if we work together, we can get past many of the common roadblocks that first-time contributors encounter! 🎉 

👀 See this page to get started: https://github.com/publiclab/plots2#installation

🖥 If you have a Windows machine, see: https://gorails.com/setup/windows/10

☁️ Or consider using Codenvy at https://codenvy.io (no invite required!)

🤝 Share the issues you encounter along the way and help others solve theirs. 💬 Chime in below in a comment to cooperate with others who are also 
working on this task.

✋ Report back at the above issue once you succeed, to encourage others and share what worked for you!

****

Noting that due to recent install of `webpacker` there's an extra step needed, apologies if this has caused you trouble!

For now, you have to create a `manifest.js` file, following the steps shown here: https://stackoverflow.com/questions/58339607/why-does-rails-fails-to-boot-with-expected-to-find-a-manifest-file-in-app-asse#answer-58370129:~:text=Easy%20Steps%20To%20Solve%20the%20Problem%3A

The error you may see for which this is the solution is:

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/jeff/.gem/ruby/2.6.6/gems/mimemagic-0.3.8/ext/mimemagic
/Users/jeff/.rubies/ruby-2.6.6/bin/ruby -rrubygems
/Users/jeff/.gem/ruby/2.6.6/gems/rake-13.0.3/exe/rake
RUBYARCHDIR\=/Users/jeff/.gem/ruby/2.6.6/extensions/x86_64-darwin-20/2.6.0-static/mimemagic-0.3.8
RUBYLIBDIR\=/Users/jeff/.gem/ruby/2.6.6/extensions/x86_64-darwin-20/2.6.0-static/mimemagic-0.3.8
rake aborted!
Could not find MIME type database in the following locations:
["/usr/local/share/mime/packages/freedesktop.org.xml",
```

The steps are:

> This error comes up because you don't have a `manifest.js` created. You need to create one, and add in a few lines to make sure things are working. In the old version of sprockets, they made big assumptions about which assets sprockets is taking care of (i.e. bundling and concatenating). Not anymore. Now you have to tell sprockets explicitly, what files you want taken care of: and you do this in your `manifest.js` file.

> Create the `manifest.js` file

`$ mkdir -p app/assets/config`

`$ touch app/assets/config/manifest.js (not the root rails directory)`

Then copy and paste the following into the manifest.js file you just created:

```
//= link_tree ../images
//= link_directory ../javascripts .js
//= link_directory ../stylesheets .css
```

If you have a precompile array in your `app/config/` folder (see below for an example) e.g. `app/config/production.rb` then perhaps you should move them over to your `manifest.js` if they are not already accessed above.

> `config.assets.precompile = ["admin.js", "admin.css"]`

> Lastly, if you are using webpacker, you might want to decide what you want handled by the asset pipeline and what you want handled by webpacker. i.e. remove the link_directory to the javascripts file according to your own particular use cases.

(added by @jywarren)

**Comment by jywarren** [comment]
Please leave comments here if you have trouble, and @publiclab/mentors and others will help each other out!

**Comment by JonathanXu1** [comment]
Hi @publiclab/mentors, I've had smooth sailing installing plots 2, but I'm having trouble running Phusion Passenger. I've followed the standard installation procedure outlined on the readme until step 9, when I get the following error:
https://pastebin.com/AaeeizLL

Here's the log file, which is quite large:
https://pastebin.com/1YinJL08

Thanks for your time!

**Comment by milaaraujo** [comment]
@publiclab/mentors, could you help @JonathanXu1?

**Comment by jywarren** [comment]
Hi, @JonathanXu1 -- and thanks @milaaraujo  for highlighting this. 

@JonathanXu1 is it possible you're running this within Windows? I see a reference to Microsoft deep in the logs. If so, perhaps take a look at #3800 and response by @gauravano:

> Ok, you can try this link - https://gorails.com/setup/windows/10 for setting up Rails on your system.

I see:

```
[ W 2018-10-28 18:36:06.7046 318/T1 Ser/AcceptLoadBalancer.h:295 ]: Cannot disable Nagle's algorithm on a TCP socket: Invalid argument (errno=22)
[ W 2018-10-28 18:36:06.7050 318/T1 Ser/Server.h:799 ]: [ApiServer] Cannot disable Nagle's algorithm on a TCP socket: Invalid argument (errno=22)
[ N 2018-10-28 18:36:06.7061 318/T1 age/Cor/CoreMain.cpp:985 ]: Passenger core online, PID 318
[ N 2018-10-28 18:36:09.9318 318/T5 age/Cor/SecurityUpdateChecker.h:517 ]: Security update check: no update found (next check in 24 hours)
[ E 2018-10-28 18:37:40.6930 318/Ti age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /mnt/c/users/jonathan/documents/coding/contests/codein/plots2: A timeout error occurred while spawning an application process.
  Error ID: 20a9843c
  Error details saved to: /tmp/passenger-error.nYzA6D
```

Hmm, actually i see you're in Ubuntu... this is mysterious -- i use Ubuntu myself! I tried searching for the error itself:

https://duckduckgo.com/?q=Implementation.cpp%3A221+Could+not+spawn+process+for+application+A+timeout+error+occurred+while+spawning+an+application+process.+phusion&atb=v121-6&ia=qa

I'm not sure what to try next, but if you get really stuck, email me at web@publiclab.org and we can get you a Cloud9 invite to try on their cloud: https://aws.amazon.com/cloud9/?origin=c9io

Sorry you're having trouble!

**Comment by shriyakaneriya** [comment]
Hello, 
I have been trying to setup plots2, but I cannot get rails to run with the OpenSSL version I have.
I am sorry I did not come across this page earlier and I have already created an issue for the same.  
Kindly refer to the issue https://github.com/publiclab/plots2/issues/3897 for details. 
Sorry for the trouble, but I would really appreciate some help here. 
Regards, 
Shriya

**Comment by jywarren** [comment]
Have folks using cloud9 had success?

Hi @shriyakaneriya - i'll check out your other page, thanks.

**Comment by jywarren** [comment]
I see at least one person using Cloud9 has the error `Could not find Bootstrap` -- this means you haven't run `yarn install` to get your JavaScript dependencies. I'm going to make sure our docs reflect this, but please give `yarn install` a try, as it replaces the former `bower install` step.

**Comment by jywarren** [comment]
Indeed, the Cloud9 instructions had not updated the `bower` command to `yarn`, and I've just made the change. In fact I believe you need to run `yarn install && yarn postinstall`. 

Here's the change I just made:

https://github.com/publiclab/plots2/blob/1c7f7ee6baa0331e36ff870157df663d92aacd5e/install_cloudnine.sh#L11

Sorry if this was getting people stuck!!!

**Comment by jywarren** [comment]
Also, if you are using cloudnine, once you begin, you should be able to run `sh install_cloudnine.sh` to begin auto-installation. I'm trying this now to be sure it works:

```
jywarren:~/workspace (master) $ sh install_cloudnine.sh 
Enter your cloud9 username: jywarren
Warning, new version of rvm available '1.29.4', you are using older version '1.29.2'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
Searching for binary rubies, this might take some time.
Found remote file https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-2.4.4.tar.bz2
Checking requirements for ubuntu.
Requirements installation successful.
ruby-2.4.4 - #configure
ruby-2.4.4 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  1 14.4M    1  254k    0     0   4864      0  0:51:48  0:00:53  0:50:55     0
```

**Comment by jywarren** [comment]
Also just linked in an issue via #3914 where it looks like `rake db:migrate` wasn't running -- but on initial setup, you actually don't need it, just `rake db:setup`. Noting here for others doing this too!

**Comment by sikfeng** [comment]
The only problem I had was that I needed to modify the ruby version in `Gemfile` (`2.5.3` for me in ArchLinux instead of `2.4.4`)

`rails test -d` gives 2 fails for me

**Comment by jywarren** [comment]
ah, can you paste your test failures into a Gist at https://gist.github.com
so we can see? Hopefully we can help you resolve them.

**Comment by thesparks** [comment]
Hi. Who can help me with `Sprockets::FileNotFound in Home#home`?

> couldn't find file 'bootstrap/dist/css/bootstrap.min.css' with type 'text/css'
> Checked in these paths: 
>   /home/sparks/plots2/app/assets/images
>   /home/sparks/plots2/app/assets/javascripts
>   /home/sparks/plots2/app/assets/less...

**Comment by atulbi** [comment]
Hi...
I'm getting 
_LoadError: Could not load the 'mongodb' Active Record adapter. Ensure that the adapter is spelled correctly in config/database.yml and that you've added the necessary adapter gem to your Gemfile._ 
when executing `rake db:setup` 
I've already copied ans pasted config/database.yml.sqlite.example as per instructions provided.

Here is full log :
https://pastebin.com/TnjrNKAk

help!

**Comment by nonas-hunter** [comment]
Hi I am a GCI participant who just figured out how to set up plots2 on my local machine. It is working surprisingly well and the instructions to set it up were very clear.

Great job Public Lab!

**Comment by okonek** [comment]
Also just installed it for GCI. Also, the app has a surprisingly good code, so congratulations for your team for keeping the code quality on the high level.

**Comment by atulbi** [comment]
@jywarren - I've copied `database.yml` from `database.yml.sqlite.example` as per given instructions.

**Comment by abizerlokhandwala** [comment]
> @sikfeng which tests failed so I don't have to scan through all the reports? Thanks!!!

Hey @jywarren 
I'm facing the same problem as @sikfeng , Ubuntu 16.04 with ruby 2.4.4
The failing tests are:
1) SearchControllerTest: https://github.com/sikfeng/plots2/blob/master/test/reports/TEST-SearchControllerTest.xml
2) SearchServiceTest: https://github.com/sikfeng/plots2/blob/master/test/reports/TEST-SearchServiceTest.xml

Thanks! :D

**Comment by JonathanXu1** [comment]
Thanks, I got plots2 working on cloud9. Is it still possible to claim this task on GCI?

**Comment by jywarren** [comment]
@JonathanXu1 -- yes, i believe so! :-)

@atulbi - that's so weird, is there any reason you can think of that `mongodb` would be called here? We don't use it anywhere in `plots2`, actually! Were you previously working on a `mongodb` project or something?

@sikfeng @abizerlokhandwala -- ok, here are the errors:

```
test_search_question_at_/search/questions/question(Minitest::Result) [/home/sikfeng/gci2018/Install plots2 on local machine/plots2/test/functional/search_controller_test.rb:35]:
Expected: 8
  Actual: 9

test_running_search_questions(Minitest::Result) [/home/sikfeng/gci2018/Install plots2 on local machine/plots2/test/unit/api/search_service_test.rb:59]:
Expected: 2
  Actual: 3
```

Have you made any changes to the codebase? Can you just confirm what database and `database.yml._____.example` you're using?

**Comment by abizerlokhandwala** [comment]
@jywarren I'm using sqlite3, and database.yml.sqlite.example, as mentioned in the installation notes

**Comment by dinaelhanan** [comment]
I ran into quiet a few errors, here's some links that helped me out!
[](https://stackoverflow.com/questions/12995271/rails-server-error-ruby-version-is-1-8-7-but-your-gemfile-specified-1-9-3)
and this for getting the "you don't have permission" error and for the nokogiri errors I was getting:
[](https://stackoverflow.com/questions/37720892/you-dont-have-write-permissions-for-the-var-lib-gems-2-3-0-directory/37956249)

**Comment by jywarren** [comment]
Great work @dinaelhanan !!

@abizerlokhandwala I'm sorry we haven't been able to solve your problem! I really can't crack it :-(

Thanks @dinaelhanan for documenting your process!

**Comment by oorjitchowdhary** [comment]
This is strange. Where did you view this error? On localhost:3000 or the terminal?

**Comment by vnallamhawk** [comment]
@oorjitchowdhary : i had this error in the localhost :)

**Comment by geekychaser** [comment]
@vnallamhawk can you please restart the server and make sure you have not made any changes.
if still you encounter this error attach a screen shot of error. thank you

**Comment by twisted-sres** [comment]
I am trying to install rvm and ruby on ubuntu, and've been running into errors, anybody here who could help me with the same?

**Comment by geekychaser** [comment]
Please describe your errors or add screen shots

**Comment by twisted-sres** [comment]
![screenshot from 2018-12-30 20-20-30](https://user-images.githubusercontent.com/36242614/50548364-3fa31180-0c71-11e9-92b3-5bc9d91de2a5.png)
I am getting this error

**Comment by oorjitchowdhary** [comment]
Have you run 'yarn install'?

Sent from my iPhone

On Dec 30, 2018, at 8:27 PM, Srestha Srivastava <notifications@github.com<mailto:notifications@github.com>> wrote:


[screenshot from 2018-12-30 20-20-30]<https://user-images.githubusercontent.com/36242614/50548364-3fa31180-0c71-11e9-92b3-5bc9d91de2a5.png>
I am getting this error

**Comment by twisted-sres** [comment]
yeah

**Comment by twisted-sres** [comment]
![screenshot from 2018-12-30 22-04-27](https://user-images.githubusercontent.com/36242614/50549215-1b4e3180-0c7f-11e9-8040-e73f87b37c48.png)
I am getting this view

**Comment by chirag-singhal** [comment]
![Uploading Screenshot from 2019-01-22 00-03-50.png…]()
I am getting this error when running passenger

**Comment by chirag-singhal** [comment]
![Uploading Screenshot from 2019-01-22 00-03-50.png…]()
I am getting this error when running passenger

**Comment by CoderJolly** [comment]
@twisted-sres Does the error still persist, pls tell the latest progress ?

**Comment by RizwanSyed357** [comment]
Hi all,

When I type 'rails console' into my terminal, whilst I am in the plots2 cloned repo, I receive this error message. I have been googling the error for a while and cannot find a solution. I am on Linux Lubuntu.

Here is the message: https://dpaste.de/VXKM

May someone please help me out with this?

**Comment by gauravano** [comment]
Hi @RizwanSyed357, you have ruby and rails installed on your system? Also, could you let us know the  bundler version you are using? Thanks!

**Comment by RizwanSyed357** [comment]
Hi @gauravano  - please see this link, which shows what version of Ruby and Bundler I have installed: https://dpaste.de/Ghpo

**Comment by gauravano** [comment]
have you tried https://stackoverflow.com/questions/19061774/cannot-load-such-file-bundler-setup-loaderror @RizwanSyed357?

**Comment by madeofhuman** [comment]
I ran into a problem when setting up the repo on my system. I followed the instructions up to `rake db:setup` where I got the error `Mysql2::Error: The used table type doesn't support FULLTEXT indexes`, which on further tracing, led me to `db/schema.rb:58`:
```

add_index "comments", ["comment"], name: "index_comments_on_comment", type: :fulltext if ActiveRecord::Base.connection.adapter_name == 'Mysql2'

```
 I also got a notification to add Mysql2 to my Gemfile.

Now, the problem is that I ran bundle install with `--without production mysql` flag, and was using the sqlite database config file, so I should not have been getting Mysql errors.

I traced the error further and got to the file `config/initializers/abstract_mysql2_adapter.rb`. When I commented out the contents of this file and ran `rake db:setup` again, everything worked fine.

**Comment by cesswairimu** [comment]
@efuet-flora is getting this error 
`Could not find gem 'tzinfo-data x86-mingw32' in any of the gem sources listed in your Gemfile.
Run bundle install to install missing gem` 
Using windows OS. Any ideas?

**Comment by gauravano** [comment]
Have you checked this -
https://stackoverflow.com/questions/29585373/could-not-find-gem-tzinfo-data-0-x86-mingw32-in-the-gems-available-on-this
?

**Comment by efuet-flora** [comment]
yes, i have @gauravano

**Comment by jywarren** [comment]
@efuet-flora posted in the chatroom an issue getting the system started:

![image](https://user-images.githubusercontent.com/24359/54285512-7e5e1d80-4578-11e9-8ee4-c68a308cbf0a.png)

![image](https://user-images.githubusercontent.com/24359/54285503-7900d300-4578-11e9-865d-e7429cac2912.png)

Copying in my response here!

Ah, Hi @efuet-flora -- it's cool you are using Puma, we have an interest in getting that working. For now, 2 things that occur to me are a) is your database software running? and b) i typically use passenger start and not rails server -- have you tried that? It uses Passenger instead of WeBrick (or in your case instead of Puma).

ah and also your first error shows in yellow text that maybe you've used a tab character instead of two spaces in your database.yml file. That could also account for your database connection not working.

**Comment by Nirvikalpa108** [comment]
Hi guys, I am installing the repo for the first time locally. I've been through the pre-reqs, but I have a question about rvm. So, I already have rbenv installed locally. Can I have rvm too? I've googled this and it seems like this is not a good idea from what I've learnt online. Please can you confirm? What would you advise if I'm already using rbenv on other projects and therefore cannot remove it? I really appreciate your help. Thank you!

**Comment by Nirvikalpa108** [comment]
Hi guys, when I try to run a unit test in my console on Mac, I get the following error message about my Ruby version not being the same as the one specified in my Gemfile:

```
Aminas-MacBook-Air:plots2 aminaadewusi$ rails test test/functional/tag_test.rb:20
Ignoring nokogiri-1.10.1 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.1
Your Ruby version is 2.6.1, but your Gemfile specified 2.4.4
```

I googled this error and indeed the error message is true, because I checked the gemfile and indeed it specifies 2.4.4 and when I run `ruby -v` in the console, it returns 2.6.1

However, I'm confused about which stackoverflow solution to follow [here](https://stackoverflow.com/questions/23039528/your-ruby-version-is-2-0-0-but-your-gemfile-specified-2-1-0). I would really appreciate your help, thank you! ❤️

**Comment by cesswairimu** [comment]
Hi @Nirvikalpa108 you need to install ruby-2.4.4, If you are using rvm use `rvm install ruby-2.4.4` after installation is done do `rvm use ruby-2.4.4` then run `bundle install` again.

**Comment by karunagoyalk** [comment]
@cesswairimu As I am working for setting up the environment in my local system..Is it working fine?
![setup](https://user-images.githubusercontent.com/16883717/54866884-e6dea300-4d9f-11e9-9b7b-f3bc3c8fd519.png)

**Comment by cesswairimu** [comment]
Yeah its fine @karunagoyalk

**Comment by simonastefan** [comment]
Hello all, if anybody else runs into errors when running the tests right out of the box with the default SQLite in development (I currently get `4 failures, 10 errors`)  consider switching to [MariaDB/MySQL](https://github.com/publiclab/plots2/blob/master/doc/TESTING.md#how-to-run-plots2-with-mysql-on-development-and-test-environments). That fixed all of them for me.
 
Some of the errors are clear that you need MySQL:
 `ActiveRecord::StatementInvalid: SQLite3::SQLException: no such function: SUBSTRING_INDEX:`
Others are not so obvious, for example:
```
    Expected: 2
    Actual: 1
    test/unit/api/search_service_test.rb:56:in block in <class:SearchServiceTest>'
```
 might be cause  `Node.search` function has considerably different code for the two DBs.

Please let me know if all the tests are supposed to be green with SQLite.

**Comment by cesswairimu** [comment]
Thanks @simonastefan for sharing your fix. Yes, some tests are failing while using SQLite3. There is a discussion of defaulting to one DBMS in the near future for all the envs to avoid this [here](https://github.com/publiclab/plots2/issues/4896). Glad you were able to setup a db that works for you :tada:

**Comment by anna-dorigo** [comment]
Hi Guys! 

I have a problem, when running rake db:setup I get this error:

rake aborted!
Mysql2::Error::ConnectionError: Access denied for user 'alejandra'@'localhost' (using password: NO)

The config\database.yml looks like this:

```
development:
  adapter: mysql2
  username: 
  password: 
  database: publiclab_dev

test:
  adapter: mysql2
  username: 
  password: 
  database: publiclab_test

production:
  adapter: mysql2
  username: 
  password: 
  database: publiclab_production
```

TIA!!!

**Comment by nstjean** [comment]
I've never worked in Ruby before. I just installed on Windows, which was a bit of a challenge! I ended up installing Ubuntu on Windows and going through that. I ran into some roadblocks but Google found me solutions.

One of note, in case anyone else has the issue: When I used `passenger start` I got a "address already in use" error. There was nothing else running on Port 3000 and changing the port didn't fix it. I found this issue already posted [https://github.com/publiclab/plots2/issues/2552](https://github.com/publiclab/plots2/issues/2552) and their solution of starting the server this way worked:
```
RAILS_ENV=production bundle exec rails s
rails s -b 0.0.0.0 -p 3000
```

**Comment by nstjean** [comment]
> I've never worked in Ruby before. I just installed on Windows, which was a bit of a challenge! I ended up installing Ubuntu on Windows and going through that. I ran into some roadblocks but Google found me solutions.
> 
> One of note, in case anyone else has the issue: When I used `passenger start` I got a "address already in use" error. There was nothing else running on Port 3000 and changing the port didn't fix it. I found this issue already posted #2552 and their solution of starting the server this way worked:
> 
> ```
> RAILS_ENV=production bundle exec rails s
> rails s -b 0.0.0.0 -p 3000
> ```

I wanted to update this and say it ended up not working on Windows no matter what I tried with Windows Subsystem for Linux. I spent today creating a dual boot system and installing Ubuntu to have a clean, happy install the way it should be.

**Comment by nicoleiocana** [comment]
@jywarren I noted that the shell script you contributed towards for easy installation is outdated now that AWS acquired Cloud9. Unfortunately, running `sh install_cloud9.sh` from the terminal and starting up the server doesn't work. I updated the script so that any individuals with AWS Cloud9 could flawlessly transition to installing plots2 on cloud.  With your permission, I would like to:

1. Create a PR to update the install_cloud9.sh file. Then, once that is approved...
2. Edit the instructions found at [Simple Installation for Cloud9](https://github.com/publiclab/plots2/wiki/Simple-Installation-for-Cloud9)

**Comment by jairus-crabb** [comment]
It was mentioned I should comment here how I was able to get plots2 up on WSL (Ubuntu 18.04). I am working on the bash terminal but I am working from files on Windows. 
1) git clone repo on the Windows C: Drive, get there with cd \mnt\c (I made a folder for projects at \mnt\c\code)
2) install Ruby using rbenv (I am a newbie and ran into a lot of issues but solved them by installing dependencies)
3) I couldn't get passenger to work with Ruby from rvm unless I used this fix: https://github.com/phusion/passenger/pull/2037/commits (not yet merged so you'll have to add this change manually). But even then I ran into dependency issues, but I'm sure someone else could figure it out.
3b) Instead when I used rbenv to install Ruby, the fix above didn't work for me. However, i was able to start the rails server with "rails s" instead of "passenger start" which uses Puma by default. 

I did this along with  the install instructions and finally got it to work. I also have VS installed and added its Windows path to Ubunutu's (which should add Windows path variable by default), and so I'm able to simply launch VS with "code <file>" from the bash terminal. DON'T do this if editing files within Ubuntu's directories, instead run an x server and install atom on Ubuntu and do that, you can edit windows files with Linux, but not the other way around.

**Comment by cesswairimu** [comment]
Awesome :tada:  thanks for outlining the steps here @jairus-crabb

**Comment by nstjean** [comment]
Hi! I'm still getting the same error when clicking on a Question in my local dev environment.

![FireShot Capture 222 - Action Controller_ Exception caught - localhost](https://user-images.githubusercontent.com/49460529/97208497-8f7d9180-1791-11eb-9d57-b71c1d260683.png)

I've tried re-installing everything and it's still happening. Anyone else run into this?

**Comment by nstjean** [comment]
Ok I've fixed it! I had to change this line:
https://github.com/publiclab/plots2/blob/72f175fb89d40fbd8f403333ea71c49722150cae/Gemfile#L27
to this:
`gem 'impressionist', '~>1.6.1'`

Per the instructions for impressionist, their version 2 is for Rails 6 and we are currently using 5.2.3
https://github.com/charlotte-ruby/impressionist#installation

**Comment by jperk224** [comment]
Hi, I am getting the below errors when trying to run `bundle install --without production mysql`

```Installing npm dependencies...
------------------------------------------------------------
Error: npm dependencies installation failed
------------------------------------------------------------
install.rb:4:in `<main>': Error while installing npm dependencies (RuntimeError)
make: *** [Makefile:4: install] Error 1

make install failed, exit code 2

# extract locations omitted

An error occurred while installing critical-path-css-rails (4.1.0), and Bundler cannot continue.
Make sure that `gem install critical-path-css-rails -v '4.1.0' --source 'https://rubygems.org/'` succeeds before
bundling.

In Gemfile:
  critical-path-css-rails
```

The out file gives me this:

```
/home/<redacted>/.rvm/gems/ruby-2.6.6/gems/critical-path-css-rails-4.1.0/lib/npm_commands.rb:47: warning: Insecure world writable dir /mnt/c in PATH, mode 040777
Installing npm dependencies...
```

When I run `gem install critical-path-css-rails -v '4.1.0' --source 'https://rubygems.org/'`

I get the same error.

Am I missing a dependency or do I need to run this as `sudo`?  I did some searching on this page and around the web but cannot seem to pinpoint what I am missing? 

Any insight is appreciated.

Thank you.

I am on WSL Ubuntu 20.04 for Win 10

**Comment by cesswairimu** [comment]
Hi @jperk224 ,
Do you have node installed already?  you could try installing it first with `sudo apt-get install nodejs` then try to run bundle install after that

**Comment by jperk224** [comment]
> 
> 
> Hi @jperk224 ,
> Do you have node installed already? you could try installing it first with `sudo apt-get install nodejs` then try to run bundle install after that

Hi @cesswairimu , thanks for writing back!  Yes I do have node installed- do I need a particular version?  Sorry if this was listed on the [prerequisites](https://github.com/publiclab/plots2/blob/main/doc/PREREQUISITES.md) page and I missed it?  I thought I had walked through all of those cleanly.

I have 10.19.0

```
/plots2$ node -v
v10.19.0
```

**Comment by cesswairimu** [comment]
no particular version...any version should be good...

does `npm install` or `yarn install` run successfully?

**Comment by jperk224** [comment]
> 
> 
> no particular version...any version should be good...
> 
> does `npm install` or `yarn install` run successfully?

Thanks @cesswairimu ! I think that was it, I was missing npm.  Apologies I thought I had it but WSL was looking to node in Windows and wasn't seeing npm.  Thanks for the help!

**Comment by Georjane** [comment]
> @Georjane do you have the redis-server installed?

Not yet @TildaDares. I noticed we had to get the standard installation up and running before doing the redis installation. Let me install that right now and give you feedback. Thank you.

**Comment by Georjane** [comment]
> @Georjane and there are still no console errors?

it just keeps trying to access the `/cable/` endpoint over and over so I had to stop this continuous process with `ctrl c`

**Comment by jywarren** [comment]
Thank you @TildaDares -- ok, so we are now moving this over to https://github.com/publiclab/plots2/issues/10844 - please see there for more!
