### ISSUE TITLE
Image upload doesn't begin on note comment

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4617]
[Ed Mallon](https://publiclab.org/profile/EdMallon) reports a comment image bug on this page:

https://publiclab.org/notes/EdMallon/02-11-2014/an-arduino-based-underwater-sensor-platform#c21724

EdMallon wrote:

> For some months now I've been unable to upload images to comment posts in this research note. I've tried multiple different browsers. Though the image selection process appears to be normal, the image upload never begins. Any ideas what might be happening? Is this research note so old it's gone into legacy status?

**Comment by jywarren** [comment]
Drag and drop seems to work, but the "choose one" link does not, in the bottom of the comment input form:

`Drag & drop to add an image or file, or choose one`

![image](https://user-images.githubusercontent.com/24359/51135827-ee665680-1808-11e9-8c68-ed26ecf6e09d.png)

**Comment by EKMallon** [comment]
On my windows system, drag & drop gives a simmilar behavior.  A + symbol appears with the world "copy" when you drag the icon of the image from windows explorer into the thread, but an upload does not initiate when you release the mouse button. Image is a jpeg from photoshop, 135 KB (139,258 bytes) on my local hard disk.

**Comment by EKMallon** [comment]
Interestingly I was able to change the photo at the beginning of the research note, but I had to go into the "legacy upload" section to do it... makes me wonder if there is some kind of security setting at my end. Same problem in chrome and explorer...

**Comment by EKMallon** [comment]
Tried to add public lab to the allow lists, but it still shows cookies as being blocked in chrome?  Same no-uploads behavior in a new copy of firefox I just downloaded and installed.  

also: the "preview"  also does not appear to do anything on all three browsers either...

**Comment by EKMallon** [comment]
OK, tried again from our mac computer (Imac Duo  osx10.7) , Safari: doesnt even respond to the login button. Firefox - again not even a response from the browser to the login button.  Chrome - logs in, but when making a post no response to either the drag-n-drop, or the choose a file when trying to add an image to a post.  Since these trials were done on a different system, I no longer think this is due to security settings on my windows machine. Has someone edited the privileges for my loginID to specifically prevent image uploads?

**Comment by jywarren** [comment]
Ok we're going to escalate this as I think there's some broader issue that
affects not only you. Thanks!

**Comment by jywarren** [comment]
OK, I believe I've tracked this to an issue from 12 days go (!!! although it may not have been published until more recently). However that only compounds the issue, since this was originally reported before then. I believe the recent issue, fixed in https://github.com/publiclab/plots2/commit/dc3bc719a139d72bf8855b4a3077c695f4643791, was the one affecting everyone. I've submitted a fix and we'll see how it does and I'll try publishing the site again. 

Once that's done, i'm going to try to reproduce again in various of the above manners. Checking back in soon.

@EKMallon THANK YOU very much for sticking with us and helping resolve this issue. We really appreciate it.

**Comment by jywarren** [comment]
OK, i've confirmed the first fix worked but:

Now I can successfully drag/drop or click to choose an image and upload it in a comment, in Chrome on ChromeOS --

Meaning i'm going to have to try to see if I can more closely replicate the originally reported issue in one of the configurations above. Thanks again for your patience.

**Comment by EKMallon** [comment]
Did some more noodling around and confirmed that this bug only affects adding images _to the comments_ below a given research note.  I have no problem adding/uploading images to the main body of the research note in any of the browsers I tested last night. ( You can see the new images I uploaded there now) but am still unable to initiate an upload to a comment.

**Comment by jywarren** [comment]
Also, shall we close this one? https://github.com/publiclab/plots2/issues/4771

**Comment by EKMallon** [comment]
Just tried again. I was able to upload a 12k png file to a new comment in
the thread, but was not able to edit an older comment to add a 112kb jpeg
file.

Now wondering if the problem was related to file size/format limits in the
first place?

Anyway I will just live with it since there's not much attention on that
old note anyway. So close the ticket.
Probably should start another Research Note anyway and see if it's just a
problem with legacy posts?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jywarren** [comment]
Hi, @EKMallon we just published a bigger revision to the comment image upload system, and are working on other parts of this now as well. Would you be willing to give it another try and tell us if we fixed a bug that helps you or if there is still an open issue? Thank you!

**Comment by jywarren** [comment]
Closing this for now, but if the issue persists, please re-open! Our comment editor has been mostly rewritten so I believe this should be resolved. Thanks.
