### ISSUE TITLE
Align the section

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5005]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** . 
* The tags goes out of alignment. It would be better if the whole Tags section will be aligned.
![Screenshot from 2019-03-11 09-54-46](https://user-images.githubusercontent.com/26685258/54101105-cf8ad780-43e7-11e9-87cd-fa13afc32af8.png)
The marked portion is below
![imageedit_2_3511708848](https://user-images.githubusercontent.com/26685258/54100460-81280980-43e4-11e9-9992-1e76f5408aab.gif)

* Update will be done in plots2/app/views/tag/_tagging.html.erb
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by gauravano** [comment]
@GettyOrawo you were looking for an issue, right? You can start with this one. Thanks!

**Comment by richa031** [comment]
hey I'm new to open source. Can I work on this issue?

**Comment by Jenniline** [comment]
Hi i am new to open source and an Outreachy applicant can i work be assigned this issue to work on?

**Comment by CleverFool77** [comment]
@GettyOrawo Are you still working on this issue. If yes, then you can open a draft PR or you ask for help in group if you came across some problem or If not, then there is no problem. As opensource is always a place where another can start from where you've left and we can assign a different contributor for this.

**Comment by vaarigupta** [comment]
hello @CleverFool77    I am an outreachy applicant and excited  to work on this issue. How can I start contributing ?

**Comment by CleverFool77** [comment]
Hi @vaarigupta Are you assigned to this issue ?

**Comment by CleverFool77** [comment]
If you are interested.
* I've added the file where the update is needed plots2/app/views/tag/_tagging.html.erb
* Here, you can check the margin /padding of the section and align it.
I hope it helps. :smile:

**Comment by gauravano** [comment]
@Priyak5 you can start with this issue. Thanks!

**Comment by Priyak5** [comment]
@gauravano okay , thank you.

**Comment by Priyak5** [comment]
Is there any way to open _tagging.html.erb file alone to check the changes made in the code? I have been trying to look for a solution online but coudn't find one.
Can anyone help me with this ?
Thank you!

**Comment by CleverFool77** [comment]
Hi @Priyak5 Do you mean the changes of lines of code you did ?
If yes, I wanted to ask you what editor you are using.
For me, I would say..I use vscode. So it shows the changes I did .

**Comment by Priyak5** [comment]
Hi @CleverFool77 I meant I want to preview the web page after the chnages are done, I am unable to do that. Do you know anything? 
Thank you!

**Comment by CleverFool77** [comment]
Hi @Priyak5 ,
After you did the local changes, you can run the project using passenger start. 
After that , your server will run and at there you can see the changes.

**Comment by Priyak5** [comment]
I am having problems while installation, so I wanted to run the file alone. Can you help me with passenger start ? Thank you @CleverFool77

**Comment by CleverFool77** [comment]
I don't think that you can run the file alone. How about starting with installation first :) .What problems you are facing ?
I'll try to give my best in help.

**Comment by Priyak5** [comment]
Error loading the 'mysql2' Active Record adapter. Missing a gem it depends on? mysql2 is not part of the bundle. Add it to your Gemfile. (LoadError)
Hey @CleverFool77  ,I am getting this error when I passenger start.

**Comment by CleverFool77** [comment]
Hi @Priyak5. Is your repo in sync with the latest commit. Coz I guess this error was resolved few days earlier.
And did you do `bundle install` or `bundle install --without production` ?

**Comment by Priyak5** [comment]
How do I sync with the latest commit ? I did bundle install

**Comment by CleverFool77** [comment]
Fetch the upstream and then you can rebase it 

Here you go 
https://medium.com/sweetmeat/how-to-keep-a-downstream-git-repository-current-with-upstream-repository-changes-10b76fad6d97

**Comment by CleverFool77** [comment]
And I'm not sure about this, but mysql gem was in the production one. So we should go for command `bundle install --without production` I guess.

**Comment by Priyak5** [comment]
Thank you @CleverFool77 , but I am still getting the mysql2 error on passenger start.

**Comment by CleverFool77** [comment]
After deleting gemfile.lock..We can try this command again..I guess.

**Comment by Priyak5** [comment]
The same error again. Thank you for your help @CleverFool77 !

**Comment by CleverFool77** [comment]
No Problem @Priyak5 I'll try my best to help. Here you go.
This is what I did. But this won't be a good method but it works .
Refork the project and and it should be in sync with current latest commit.
try installation again but with the command of without production.
I guess this will work. COz this always works with me ;p

**Comment by Priyak5** [comment]
I tried your method but now I am getting a new error. Any idea what this is ? ;_;
![Screenshot from 2019-03-23 21-54-51](https://user-images.githubusercontent.com/32927328/54865228-49c44000-4d88-11e9-8a34-81b21d0fca15.png)

**Comment by CleverFool77** [comment]
After what command you got this?
You did yarn install ?

**Comment by Priyak5** [comment]
It worked. Thank you soooo much @CleverFool77

**Comment by CleverFool77** [comment]
Oh greaaaaattttttt..Congrats @Priyak5 :tada: :tada: 
Now on the rails :nerd_face:

**Comment by Priyak5** [comment]
@CleverFool77 Thanks alot!!
I am facing a problem in alignment, when tags are created they are aligned and when deleted from rows other than the first row are deleted correctly, when a tag from 1st row is deleted the alignment is not correct. Any idea why?
I used alignment in the div tag.

**Comment by CleverFool77** [comment]
HI @Priyak5 Can I have screenshot of the change you did ?

**Comment by Priyak5** [comment]
@CleverFool77 the screenshot of the webpage or code snippet ?

**Comment by CleverFool77** [comment]
Both of them would be great.

**Comment by Priyak5** [comment]
I made divisions using the div tag to see the alignment. 
The screenshots have border,which I added just for checking purpose.
When I remove all tags excluding the one in the first row the alignment of tag goes wrong.
![Screenshot from 2019-03-24 16-37-11](https://user-images.githubusercontent.com/32927328/54875434-39ae6e00-4e25-11e9-9f90-3120a6be4b1f.png)
![Screenshot from 2019-03-24 16-37-40](https://user-images.githubusercontent.com/32927328/54875435-3f0bb880-4e25-11e9-99fc-e64df4c7b1a7.png)

**Comment by CleverFool77** [comment]
Hi @Priyak5 I'm travelling right now. So can't understand it clearly from the image. Can I have screenshot of code. And in the image, it looks like you have aligned them. But actually if you'll look closer, you'll realise that they are not aligned.
The div in every section makes it bit thicker. So here tag title is aligned to inner part of that black border. Whereas the tags below is aligned to outer part of black border. 
Due to thickness of div line you added, they look they are aligned to one line. But in actual, that's three divs.

**Comment by Priyak5** [comment]
hey @CleverFool77 sorry to disturb you again and again
![Screenshot from 2019-03-25 03-46-42](https://user-images.githubusercontent.com/32927328/54882694-a1df6d00-4e82-11e9-94cb-b3c2e75e2059.png)
![Screenshot from 2019-03-25 03-46-50](https://user-images.githubusercontent.com/32927328/54882698-a73cb780-4e82-11e9-85e3-344217895a8e.png)

**Comment by CleverFool77** [comment]
hi @Priyak5 .
Before the screenshot, Did you try this ?


> And in the image, it looks like you have aligned them. But actually if you'll look closer, you'll realise that they are not aligned.
> The div in every section makes it bit thicker. So here tag title is aligned to inner part of that black border. Whereas the tags below is aligned to outer part of black border.
> Due to thickness of div line you added, they look they are aligned to one line. But in actual, that's three divs.

**Comment by MoretS** [comment]
Hello @CleverFool77 @gauravano !

Is this issue still in progess? If yes, I would be happy to work on it 😄

**Comment by gauravano** [comment]
Hi @MoretS, 

The UI has changed now as you can see - https://publiclab.org/wiki/requests. So, I guess this issue in not valid anymore. @cesswairimu @jywarren please confirm.

Although, I can see an issue with the alignment of Social Sharing pills at end of sidebar. (From this page - https://publiclab.org/wiki/name-your-project-here)

<img width="318" alt="tagss" src="https://user-images.githubusercontent.com/20878070/94366184-f278fb80-00f3-11eb-8d3c-2f51c6f6732f.png">

Have opened a issue regarding this - https://github.com/publiclab/plots2/issues/8431. if you want, you can claim it and start working on it :)

Thanks!

**Comment by jywarren** [comment]
That's right, thank you @gauravano -- moving over to #8431 then! Thanks all!
