### ISSUE TITLE
Exact username MATCH addition on API profile search query

### ISSUE THREAD

**Issue by rarrunategu1** [publiclab/plots2#5775]
We need to ensure that the API profile search query returns exact match on username as well.  Right now, if a common name is entered in the search query it will return other names and not the exact query we're calling.

**Comment by gauravano** [comment]
Hi @rarrunategu1, thanks for reporting. Would you like to improve the search API? Thanks!

**Comment by rarrunategu1** [comment]
Yes. thank you.

**Comment by gauravano** [comment]
Great!

**Comment by rarrunategu1** [comment]
@gauravano I'd like to test some code but I need to test a username amongst usernames.  I only have the admin signed in with no users to search.  I would like to create a situation with usernames on the system and searching a particular name.  I tried creating some users on rails console but then realized that it wouldn't give me a user "lot" search.  Any suggestions you could help me with?

**Comment by jywarren** [comment]
Hi Rose, can you clarify what you mean by a user "lot" search? Thanks!

**Comment by rarrunategu1** [comment]
Hi @jywarren , I meant like a bunch of users.  A search in a "lot" of users....probably not the best word to use.

**Comment by jywarren** [comment]
Hm, so if you wanted to you could make a variety of users following the seeds.rb example:

https://github.com/publiclab/plots2/blob/05ec8a29b19e33090604cc070319ff5686abd6ce/db/seeds.rb#L12-L20

This segment of code generates a bunch of tags:

https://github.com/publiclab/plots2/blob/05ec8a29b19e33090604cc070319ff5686abd6ce/db/seeds.rb#L83-L85

So maybe something like:

```ruby

# create a bunch of random tags
20.times do
  uniqueNum = (Time.now.to_i + rand(100)).to_s
  user = User.create! "username" => "user#{uniqueNum}",
    "email" => "user#{uniqueNum}@example.com",
    "status" => 1,
    "openid_identifier" => nil,
    "password" => "password",
    "password_confirmation" => "password"
    user.role = "basic"
  user.save()
end
```

**Comment by jywarren** [comment]
Then you should be able to search for `user` and get like 20+ results!

**Comment by gauravano** [comment]
Or, you can test on unstable? You can do changes, push them on `unstable` and your code will be live at https://unstable.publiclab.org after building. As unstable has lot of data, it would be like testing in the production. 

And, @jywarren's approach is there too. Also, we can use https://github.com/stympy/faker for generating fake data in seeds.rb too. Hmm, it's something which we can do for all :thinking:

**Comment by rarrunategu1** [comment]
Hello, I'm having a little trouble testing on unstable.  I pushed to unstable and checked the website listed but I don't notice anything changing at all.  All I have to do is push it and then check the website right?  My apologies this is all new to me.

**Comment by cesswairimu** [comment]
Hey @rarrunategu1 :wave: , I checked the latest commits on unstable https://github.com/publiclab/plots2/tree/unstable and your changes do not seem to be there...maybe you pushed to your fork...
You can run this command to force push to plots2/unstable `git push -f https://github.com/publiclab/plots2 HEAD:unstable` after about 20 mins your changes should be visible on https://unstable.publiclab.org. Feel free to ping me if you have any further questions or problems.

**Comment by rarrunategu1** [comment]
Do I need to have permission to push?  I changed my remote to publiclab/plots2 and attempted pushing the information but I'm getting this error.  

remote: Permission to publiclab/plots2.git denied to rarrunategu1.

**Comment by gauravano** [comment]
Hi @rarrunategu1, yes, you need permission for pushing to unstable. tagging @jywarren if he can provide permission right now. 

Also, if you want to test your work right now, feel free to pass the link to your PR and I can push that to `unstable` for you.

**Comment by rarrunategu1** [comment]
I did a pull request to go into the unstable branch.  @gauravano would you please let me know when I can check it?  I really appreciate all your help with this.

**Comment by gauravano** [comment]
I have pushed it as you can see your PR merged. You can see your PR building https://jenkins.laboratoriopublico.org/job/Plots-Unstable/lastBuild/console and it'll take 10-15 mins to build. After that, head over to http://unstable.publiclab.org for testing your work

**Comment by gauravano** [comment]
@rarrunategu1 your work is live at unstable.publiclab.org and just to confirm, the last commit in this - https://jenkins.laboratoriopublico.org/job/Plots-Unstable/lastBuild/changes list of commits is your's, right?

**Comment by jywarren** [comment]
my apologies on permissions, adding them now.

**Comment by rarrunategu1** [comment]
Hello, unfortunately I still don't have permission.  
![image](https://user-images.githubusercontent.com/29240939/58999836-cbe3d280-87d5-11e9-9a09-4eb41c6c19a6.png)

**Comment by jywarren** [comment]
Hmm, Gaurav is this how you do it?

**Comment by gauravano** [comment]
Yes! Adding a guide in our docs too - https://github.com/publiclab/plots2/pull/5847

**Comment by rarrunategu1** [comment]
Thank you @gauravano.  I've added my review.  @jywarren I still don't have permission to push.  I'm stuck right now because my next step also has to do with the questions Iisted on my review on #5847

**Comment by gauravano** [comment]
You want to push more commits?

**Comment by rarrunategu1** [comment]
yes, unfortunately the  commit I pushed did not achieve what I wanted it to.
